### ISSUE TITLE
Working Great

### ISSUE THREAD

**Issue by hhuitema** [yo-han/Home-Assistant-Carelink#14]
Hi,

I have been using your integration since your initial version. The improvements you made are great.
Especially the three leading values being Last Glucose, Last Glucose Trend and Active Insuline are heavily in use for monitoring. From this week i intend to start using these values for notifications.

A smallobservation, the Active Insuline value is sometimes 'not available' even though there are values in the JSON. 

Quite often the carelink service itself is not responding or the communication from the 'conduit' to the cloud is not working.
Then obviously any sensor values are defaulted or empty. 
I know all the 'sensor' values are in the json for 24 hours, but i have no clue if it is possible to update the sensor 'recording' in homeassistant.

In any case, here is a screenshot of my current CGM dashboard. :)

![image](https://user-images.githubusercontent.com/112881392/212838449-f3a6fc69-dd37-4b0a-8c60-48c90f1727fd.png)

**Comment by yo-han** [comment]
Nice dashboard! I know the Carelink service is unavailable a lot. And the bt connection between pump en conduit is even worse. We tried a lot to work around these issues but they are completely out of my hands.

I can take a look at the active insuline value. If it's in the JSON is should also be visible in the integration.

The recording is done automatically at every change of a sensor. If a sensor shows as unavailable it is because the value could not be retrieved from the JSON export.
